### ISSUE TITLE
SketchUp 2022 Mac minor graphic glitch, blinking currently selected tool

### ISSUE THREAD

**Issue by DavidGoldwasser** [openstudiocoalition/openstudio-sketchup-plugin#103]
This doesn't seem to impact function, but it is new to 2022 vs. 2021. When the SketchUp Plugin extension isn't loaded this doesn't blink, it is just solid selected state. As soon as I load the extension it blinks. Everything still functions now. It blinks about 5x a second, I can do video if needed. Note that this only happens with the tool icon that is part of the model window. The same icon on the stand alone toolbar doesn't blink. Its possible this is SkechUp issue and that nothing can be done in plugin to fix it. Either way it is very minor, hardly work mentioning.

![Screen Shot 2022-02-02 at 4 26 19 PM](https://user-images.githubusercontent.com/4857055/152255949-d4bed343-83ad-4965-9807-50ba7bc04c20.png)

**Comment by macumber** [comment]
Thanks @DavidGoldwasser, I suspect it is related to https://github.com/openstudiocoalition/openstudio-sketchup-plugin/commit/4f0f568362a6e4b702aebd5b194da9176b41e30d
