### ISSUE TITLE
Error loading OpenStudio Plug-In for Sketchup 2022

### ISSUE THREAD

**Issue by treemuel** [openstudiocoalition/openstudio-sketchup-plugin#105]
I keep receiving the following message when trying to load the plug-in for Sketchup 2022. I believe I downloaded the appropriate version (1.3.1). Any help would be greatly appreciated, thank you!

Error loading OpenStudio SketchUp
Plug-In:
dlopen(/Applications/
OpenStudioApplication-1.3.1/Ruby/
openstudio_modeleditor.bundle,
0x0009): tried: '/Applications/
OpenStudioApplication-1.3.1/Ruby/
openstudio_modeleditor.bundle'(mach-
o file, but is an incompatible architecture
(have '×86_64', need 'arm64e')) - /
Applications/
OpenStudioApplication-1.3.1/Ruby/
openstudio_modeleditor.bundle
Do you want to check the version
compatibility matrix
<img width="270" alt="Screen Shot 2022-04-24 at 12 15 22 PM" src="https://user-images.githubusercontent.com/104320852/164990748-951b37af-a15e-477a-8fd3-771b4890de98.png">
?

**Comment by macumber** [comment]
It looks like you have a new ARM based Mac is that right?  I think we will have an ARM based installer for the next OpenStudio 1.4.0 release.  In the meantime, does SketchUp offer an x86 based installer for Mac?  Does that work for you?

**Comment by treemuel** [comment]
Thanks for the response. 
Yeah, it's a newer Mac with the M1 chip. As far as I can tell, there's only one Sketchup installer for MacOSX. Or are you suggesting running the Windows version off an emulator? I suppose I could also wait for the 1.4.0 release...

**Comment by macumber** [comment]
I think the SketchUp installer automatically detects that you have an M1 chip and automatically installs binaries built for that chip.  That is what this message is saying: `is an incompatible architecture (have '×86_64', need 'arm64e'))`

The best solution will be to use the OpenStudio Application 1.4.0 package built for M1 once [this issue](https://github.com/openstudiocoalition/OpenStudioApplication/issues/505) is fixed and 1.4.0 is released.

In the meantime, you could try running SketchUp in a Windows emulator.

**Comment by macumber** [comment]
@treemuel the M1 compatible arm64 packages for 1.4.0 are now available at https://github.com/openstudiocoalition/OpenStudioApplication/releases/tag/v1.4.0
