### ISSUE TITLE
Sketchup 2022 w Openstudio 1.4.0 crashes w opening file

### ISSUE THREAD

**Issue by LReif** [openstudiocoalition/openstudio-sketchup-plugin#112]
Instaled sketchup 2022 and the openstudio 1.4.0 but its not working. when i try to opend a file it closes itself.
working on win11
Can anyone help me?

**Comment by macumber** [comment]
Can you provide a little more information about which program is crashing?  Is it the OpenStudio Application?  Can you follow some of the troubleshooting tips at https://openstudiocoalition.org/getting_started/troubleshooting/ and see if those help?
