### ISSUE TITLE
sketchup-plugin v1.6

### ISSUE THREAD

**Issue by GhorabMG** [openstudiocoalition/openstudio-sketchup-plugin#122]
Hello,
 
Openstudio-sketchup-plugin.rbz  file for v1.6 is not available for download.

I appreciate if you include Openstudio-sketchup-plugin.rbz as part of the asset files for V1.6.
Thank you,

**Comment by macumber** [comment]
Thanks for reporting, for some reason the previous upload failed, it is there now
