### ISSUE TITLE
Model disappears after reopening osm file (but works in openstudio app)

### ISSUE THREAD

**Issue by jrabmal** [openstudiocoalition/openstudio-sketchup-plugin#127]
In some cases a model built with the plugin can't be reopened again.

The model works fine while editing and no error is shown but it can't later be reopened normally using the plugin. No special operation seems to trigger this behaviour and the information appears to be there as the model can be opened and edited normally in OpenStudioApp.

The attached model, built from scratch using the plugin, shows this problem. It doesn't show up in the sketchup plugin but works with the OpenStudio App.

The sketchup version used is 23.0.419 (64 bit) (Pro version) and the plugin version used is 1.6.0. The OpenStudioApp version used to view the resulting model is 3.6.1.

[RM05_aislada_not_working.zip](https://github.com/openstudiocoalition/openstudio-sketchup-plugin/files/13278896/RM05_aislada_not_working.zip)

**Comment by macumber** [comment]
I think this issue might be fixed by https://github.com/openstudiocoalition/openstudio-sketchup-plugin/pull/123, I will try it out this weekend

**Comment by macumber** [comment]
This fix will be included in the next release of OpenStudio SketchUp Plug-in which should be in December
