### ISSUE TITLE
Show/Indicate Surface’s Normal Vector in Sketchup OpenStudio Plugin

### ISSUE THREAD

**Issue by ianvg** [openstudiocoalition/openstudio-sketchup-plugin#128]
It would be nice to have some indication of whether or not a wall surface is pointing inwards or outwards. Right now the only way I can tell before diagnostics or errors, is the color. Darker yellow is outside facing and tannish-yellow is inwards facing. This would really help with folks who cannot see color as well.

Edit: This comes from a [post](https://unmethours.com/question/93567/showindicate-surfaces-normal-vector-in-sketchup-openstudio-plugin/) I made on Unmet Hours.

**Comment by macumber** [comment]
Hey @ianvg check out the "Render by Surface Normal" option, https://openstudiocoalition.org/reference/sketchup_plugin_interface/#rendering-modes, I think this does what you want?

**Comment by macumber** [comment]
Assuming "Render by Surface Normal" is sufficient unless I hear anything more from @ianvg
