### ISSUE TITLE
openstudio-sketchup-plugin

### ISSUE THREAD

**Issue by poppopppp** [openstudiocoalition/openstudio-sketchup-plugin#129]
Can we use Sketchup Pro 17 with openstudio-sketchup-plugin v.1.6? When launching SketchUp after installing the plugin, the program asked path to openstudio root directory. Then, i input c:/openstudioapplicaiton-1.6.0 and got the message saying that error loading openstudio sketchup plug-in: 126: the specified module could not be found - /ruby/openstudio.so

We are using Sketchup Pro 17.  How can we install openstudio sketchup plugin?

Thank you for your help advance.

**Comment by macumber** [comment]
SketchUp 2017 used Ruby 2.2.4.  The last version of the OpenStudio SDK to support that version of Ruby was [OpenStudio 2.9.1](https://github.com/NREL/OpenStudio/releases/tag/v2.9.0): 

https://github.com/NREL/OpenStudio/wiki/OpenStudio-SDK-Version-Compatibility-Matrix

That was the last release that the OpenStudio Application and OpenStudio SketchUp Plug-in was still bundled with the OpenStudio SDK.  They are now available separately, see [this post](https://openstudio.net/news/1536268924) for more information.

The versions of SketchUp compatible with the newer, separate OpenStudio Application and OpenStudio SketchUp Plug-in packages are listed at https://github.com/openstudiocoalition/openstudio-sketchup-plugin/wiki/OpenStudio-SketchUp-Plug-in-Wiki.
