### ISSUE TITLE
This sub surface is not contained by its base surface, it cannot be drawn.

### ISSUE THREAD

**Issue by kitty9385** [openstudiocoalition/openstudio-sketchup-plugin#130]
Hello, expert.

I am using OpenStudio-3.6.1 / OpenStudioApplication-1.6.0 / SketchUp 2022.

I got the .osm file from SketchUp and it looks like the picture below.
This sub surface is not contained by its base surface, it cannot be drawn.

What is the reason?

I also attached the osm file.

Please help me.
It can be awkward because I used a translator.
Thank you.

<img width="421" alt="스크린샷 2023-11-24 오후 7 00 35" src="https://github.com/openstudiocoalition/openstudio-sketchup-plugin/assets/150419459/e0f50fbe-bca9-4587-8bf8-4887eb4c04a9">
[file.zip](https://github.com/openstudiocoalition/openstudio-sketchup-plugin/files/13457773/file.zip)

**Comment by macumber** [comment]
Hi @kitty9385 this means that your subsurface (window, door, or skylight) vertices are either touching the edge of the base surface (wall or roof) or they extend past the edge of the base surface.  It is recommended that window or skylight vertices are offset at least 1 inch from the edge of the base surface.  Door vertices can interset one edge of the base surface but not more.
