### ISSUE TITLE
invalid blank Outside Boundary Condition Object

### ISSUE THREAD

**Issue by kitty9385** [openstudiocoalition/openstudio-sketchup-plugin#131]
Hello.
I'm a beginner.
I can't solve this.

** Severe  ** FenestrationSurface:Detailed="FACE 3839", invalid blank Outside Boundary Condition Object
   **   ~~~   ** ...when Base surface uses "Surface" as Outside Boundary Condition Object, subsurfaces must also specify specific surfaces in the adjacent zone.

I don't know what needs to be in the blank.

Why should I fill in this blank?
I want to make sure that the error does not appear even if I leave the blank.
What should I do?

Please give me an example as well.

It's awkward using a translator.
Thank you..

<img width="1132" alt="스크린샷 2023-11-26 오후 7 21 22" src="https://github.com/openstudiocoalition/openstudio-sketchup-plugin/assets/150419459/bdd641a0-72e6-46f6-b5d0-70a2ce95f5a2">

[file1.zip](https://github.com/openstudiocoalition/openstudio-sketchup-plugin/files/13466504/file1.zip)

**Comment by Ski90Moo** [comment]
@kitty9385 this is not the forum for help with OpenStudio.  It is intended to lodge issues with the software.  Please see unmethours.com.  

This video will help solve your problems: https://youtu.be/FfIpsCsO7HM?si=ORWcWQFELgfdazdc
