### ISSUE TITLE
New 1.7 Sketchup plugin is actually 1.6 version

### ISSUE THREAD

**Issue by iansabourin-somers** [openstudiocoalition/openstudio-sketchup-plugin#135]
The plugin made available here: [openstudio-sketchup-plugin.rbz](https://github.com/openstudiocoalition/openstudio-sketchup-plugin/releases/download/v1.7.0/openstudio-sketchup-plugin.rbz)

is actually still the 1.6 version and can't process osm files from OpenStudio v1.7. 
@macumber 

Thank you for your time

**Comment by macumber** [comment]
Hi @iansabourin-somers, are you looking at the version of the OpenStudio SketchUp Plug-in in the "Extensions->OpenStudio->About OpenStudio" dialog?  It looks like I did miss updating the "SketchUp Plug-in Version" in that dialog.  Thanks for pointing that out. 

However, tIhe OpenStudio SketchUp Plug-in can be pointed to different versions of the OpenStudio Application. The OpenStudio Application actually sets the version of OpenStudio SDK and versions of OSM files.  In the OpenStudio SketchUp Plug-in, you can go to "Extensions->OpenStudio->Preferences", choose the OpenStudio Application version you want in the "OpenStudio Root Directory" property, save and then restart SketchUp.  Then you should be able to open 1.7.0 version OSM files.

**Comment by macumber** [comment]
I've fixed the RBZ at https://github.com/openstudiocoalition/openstudio-sketchup-plugin/releases/tag/v1.7.0 to have the correct version

**Comment by iansabourin-somers** [comment]
> I've fixed the RBZ at https://github.com/openstudiocoalition/openstudio-sketchup-plugin/releases/tag/v1.7.0 to have the correct version

Indeed, the method you suggested in the previous comment fixed the problem I had (see screenshot for reference).
Thank you very much !

![Capture d’écran 2024-03-04 092603](https://github.com/openstudiocoalition/openstudio-sketchup-plugin/assets/43706734/d044fb1e-460e-4d76-8b44-a31f2e196705)
