### ISSUE TITLE
Adjusting the building square footage of an existing osm in SketchUp

### ISSUE THREAD

**Issue by Safari-2024** [openstudiocoalition/openstudio-sketchup-plugin#136]
I have a detailed OpenStudio model for a midrise residential building and I need to create multiple versions of it with different total building square footages. I scaled down my geometry in SkechUp Plugin but when I reopen the modified model, the edits are not there and the geometry looks broken (see the attached pictures). I did run the simulation with the modified model, I didn't get any error but the total square footage in the report is still the same as my original model. It looks like that the SketchUp scaling option doesn't work. Is this a common issue? Can anyone think of a solution?
<img width="416" alt="SketchUp Plugin" src="https://github.com/openstudiocoalition/openstudio-sketchup-plugin/assets/168171475/e27f838a-4c9b-4bf2-9a39-0db5dd3beb1d">

**Comment by macumber** [comment]
I don't think SketchUp Plug-in responds correctly to the scale tool in SketchUp.  An alternative is to use the scale geometry measure at https://bcl.nrel.gov/content/f9cc2ffc-2838-4a18-8330-97e7cc94cdf8.
