### ISSUE TITLE
openstudio-sketchup-plugin v1.8.0

### ISSUE THREAD

**Issue by MrAshin1** [openstudiocoalition/openstudio-sketchup-plugin#144]
I download the openstudio-sketchup-plugin v1.8.0-Pre-release installed in SU, however, the info of plugin also shows v1.7.0.
However, my openstudio version is v1.8.0. When I have simulated the model, then I need to use plugin to open the latest version of osm. file. It will show v1.7.0 can not open the file of v1.8.0.

![image](https://github.com/user-attachments/assets/5df61c33-025d-4078-9329-2475be3f0ba0)
![image](https://github.com/user-attachments/assets/64004a46-47f7-4401-bc1d-17de37841751)
![image](https://github.com/user-attachments/assets/d3d53ec1-19b3-45ef-b6b1-fa5bc4f6f3d1)

**Comment by macumber** [comment]
Thanks @MrAshin1, this is fixed in https://github.com/openstudiocoalition/openstudio-sketchup-plugin/releases/tag/v1.8.0-rc.2

**Comment by MrAshin1** [comment]
> Thanks @MrAshin1, the plug-in version shown is fixed in https://github.com/openstudiocoalition/openstudio-sketchup-plugin/releases/tag/v1.8.0-rc.2
> 
> However, I think your main issue is that you have pointed your plug-in to OpenStudio Application 1.7.2. If you want to open an OSM made with OS SDK 3.8.0 then you will need to point your plug-in to the OpenStudio Application 1.8.0 or higher. This will require using SketchUp 2024 or newer as OS SDK was updated to Ruby 3.2.2. See these version compatibility matrices for more information:
> 
> https://github.com/NREL/OpenStudio/wiki/OpenStudio-SDK-Version-Compatibility-Matrix https://github.com/openstudiocoalition/OpenStudioApplication/wiki/OpenStudio-Application-Version-Compatibility-Matrix https://github.com/openstudiocoalition/openstudio-sketchup-plugin/wiki/OpenStudio-SketchUp-Plug-in-Wiki#openstudio-sketchup-plug-in-version-compatibility-matrix

The problem has been solved. Really thank!!!
