### ISSUE TITLE
Error loading OpenStudio SketchUp Plug-in - File does not exist 

### ISSUE THREAD

**Issue by papisunny** [openstudiocoalition/openstudio-sketchup-plugin#150]
Hello everyone,

I’m looking to use OpenStudio because it seems essential for working with EnergyPlus and SketchUp. I’ve installed the OpenStudio plugin, and based on the installation notes, it appears I also need the OpenStudio application itself, which I have installed as well.

However, when I launch SketchUp, a window pops up prompting me to set the source folder and to install OpenStudio. I’ve tried pasting the directory path, but it doesn’t work. I attempted using the application directory path and the path from the library folder, but neither resolved the issue.

I’ve also searched my computer for the file named openstudio_modeleditor.rb but couldn’t find it. Additionally, I reinstalled both the plugin and the application, ensuring all necessary components, including the Ruby folder, were installed. However, this particular file doesn’t seem to exist on my system.

I’ve noticed other posts discussing this topic; however, they don’t have the same computer configuration or file versions. My issue might be related to these differences.

I’ve included screenshots of the error messages, the source folders I’ve tried setting in the SketchUp interface, and a screenshot showing my computer specs.

Any assistance on how to resolve this problem would be greatly appreciated!

Thank you.

<img width="328" alt="computer informations" src="https://github.com/user-attachments/assets/8917b171-0451-4396-83dc-094a7d191d17">
<img width="356" alt="error message 1" src="https://github.com/user-attachments/assets/e40a460c-9dbb-469a-90ea-f5f996b821c1">
<img width="315" alt="error message 2" src="https://github.com/user-attachments/assets/8d89674d-0ac1-4d8d-872c-1a39a9cddb88">
<img width="1060" alt="file indicated unsuccessfully in application" src="https://github.com/user-attachments/assets/26b6a1a8-8707-4d15-9fd3-124ad5d07b49">
<img width="1922" alt="file indicated unsuccessfully in library" src="https://github.com/user-attachments/assets/3293e79f-daeb-4c9a-9a26-d8a228928f1b">
<img width="743" alt="installed versions" src="https://github.com/user-attachments/assets/d2b77b72-862f-455b-bd5d-573e4442f7df">

**Comment by macumber** [comment]
Hi @papisunny, you need to install [OpenStudio Application 3.8.0](https://github.com/openstudiocoalition/OpenStudioApplication/releases/tag/v1.8.0) and point the OpenStudio SketchUp Plug-in at that.  See https://github.com/openstudiocoalition/openstudio-sketchup-plugin/wiki/OpenStudio-SketchUp-Plug-in-Wiki#openstudio-sketchup-plug-in-version-compatibility-matrix for more information

**Comment by papisunny** [comment]
I’ve already done that; however, the error message persists. Here is the path I’m indicating to SketchUp: /Applications/OpenStudio-3.8.0

SketchUp continues to display this message: 
File ‘/Applications/OpenStudio-3.8.0/Ruby/openstudio_modeleditor.rb’ does not exist.

I manually checked if this file ‘openstudio_modeleditor.rb’ exists, but I can’t find it (neither in Applications nor by going through Library/application support).

I hope you can help me for this issue.

**Comment by macumber** [comment]
You need to point it at `/Applications/OpenStudioApplication-1.8.0`, OpenStudio and OpenStudio Application are separate projects that have separate installers.

**Comment by papisunny** [comment]
Thank you so much ! That is finally working. Have a good day Macumber !
