### ISSUE TITLE
Path to OpenStudio Application is incorrect

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/openstudio-sketchup-plugin#2]
When I click in "Launch Openstudio" a message appears : " Windows couldn´t find \OpensStudioApp"....

https://unmethours.com/question/41430/openstudio-100-pre-1-installation-problem/?comment=41561#post-id-41561

**Comment by eomere** [comment]
I encounter this issue as well. I noticed that is it specific to the Windows version of the Plugin. The "Launch OpenStudio" icon on the Mac version of the Plugin executes.

**Comment by DavidGoldwasser** [comment]
The dialog "Path to OpenStuido Root" not very descriptive, could say "Path to OpenStudio Application Directory". At least on mac with the final installer it doesn't auto-fill this out. If you get it wrong, it never comes up again even if you delete the plugin, unless you know to hand edit PrivatePreferences.json. It would be nice on every launch for the dialog to pop up if the path isn't found, so the user has a chance to enter it within the SketchUp GUI. Also, on mac the dialog is very small, so hard to read the path you enter paste 

<img width="1000" alt="Screen Shot 2020-05-22 at 8 35 34 AM" src="https://user-images.githubusercontent.com/4857055/82681070-72ed9400-9c0a-11ea-9328-f35ab38c6cd4.png">

**Comment by macumber** [comment]
@eomere this works for me on Windows with OpenStudioApplication 1.0.0 or higher.  What version of OpenStudio are you linking the plug-in with?  Are you using OpenStudio 2.9.1 (prior to the app separation)?
