### ISSUE TITLE
Check For Updates Functionality Does Not Execute

### ISSUE THREAD

**Issue by eomere** [openstudiocoalition/openstudio-sketchup-plugin#5]
The Check For Updates feature *should* return a dialogue box that reveals if there is/isn't a new update. To access this feature: **Extensions/OpenStudio/Check For Update**. Nothing happens after one clicks **Check For Update**. This issue is present within both the Windows and Mac Versions of the Plugin.

**Comment by jmarrec** [comment]
What version did you use? On 2.9.1 I get this:

![image](https://user-images.githubusercontent.com/5479063/77425910-c0e54780-6dd3-11ea-9a57-70f85684012a.png)

**Comment by eomere** [comment]
We used the Plugin within Sketchup Pro 2019 and the OpenStudio App 1.0.

**Comment by macumber** [comment]
Fixed in https://github.com/openstudiocoalition/openstudio-sketchup-plugin/pull/48
