### ISSUE TITLE
Bring over docs and scripts from OpenStudio?

### ISSUE THREAD

**Issue by jmarrec** [openstudiocoalition/openstudio-sketchup-plugin#59]
https://github.com/NREL/OpenStudio/blob/1773b54ce1cb660818ac0114dd7eefae6639ca36/SketchUpInstallName.rb

https://github.com/NREL/OpenStudio/blob/1773b54ce1cb660818ac0114dd7eefae6639ca36/developer/ruby/OpenStudioSketchUpPluginRDoc.rb

https://github.com/NREL/OpenStudio/blob/1773b54ce1cb660818ac0114dd7eefae6639ca36/developer/doc/Building%20and%20Testing%20OpenStudio.md#sketchup-extension-signature

cf https://github.com/NREL/OpenStudio/issues/4058

**Comment by macumber** [comment]
Thanks @jmarrec we'll need to the SketchUpInstallName for 1.1.0

**Comment by jmarrec** [comment]
It's already at https://github.com/openstudiocoalition/OpenStudioApplication/blob/develop/SketchUpInstallName.rb

**Comment by macumber** [comment]
@jmarrec I am ok to remove all of those linked items from the OpenStudio repo, I just don't have rights to do so

**Comment by jmarrec** [comment]
It's already gone from the SDK repo. The links are to a specific commit (permalink), but it's been cleaned on develop.
