### ISSUE TITLE
OpenStudio Inspector does not recognised a "copied and pasted" Glare Sensor

### ISSUE THREAD

**Issue by eomere** [openstudiocoalition/openstudio-sketchup-plugin#6]
In order to create a new object, a User can typically copy and paste an existing object. When an existing Glare Sensor is copied and pasted, the resulting new Glare Sensor is not recognized by the OpenStudio Inspector. The resulting error message reads, *"Unknown object of type OpenStudio::GlareSensor added"*. This issue is present within both the Windows and Mac versions of the Plugin. 

On scanning the OpenStudio Inspector, I realized that the name of the object type for a Glare Sensor is **OpenStudio:Glare:Sensor**. This contradicts the name of the object type for a pasted Glare Sensor, **OpenStudio::GlareSensor**. The location of the second colon within both names differ. I believe this discrepancy triggers this error.

**Comment by jmarrec** [comment]
![image](https://user-images.githubusercontent.com/5479063/77426888-b5931b80-6dd5-11ea-87a9-0224fedafb6f.png)
