### ISSUE TITLE
The source code in the latest release rbz file is not the source code for that release

### ISSUE THREAD

**Issue by camspiers** [openstudiocoalition/openstudio-sketchup-plugin#61]
If you cross check the rbz contents with the zip contents from the same release, you will find they are very different. It is almost like an old rbz file was uploaded. I noticed this when attempting to use the "Create spaces from diagram" dialog, and eventually figuring out that old source code is being use, in particular source code that was attempting to reference "Sketchup::Face" constant, but instead was referencing "Face" causing the constant to resolve to the "OpenStudio" module and therefore not be found. See `SpaceDiagramInterface.rb` for an example of discrepancies between the rbz contents and the zip/master source contents.

**Comment by macumber** [comment]
Thanks for the report @camspiers, this is unfortunately true.  I tagged version v1.0.1 and submitted that to the SketchUp extension warehouse as v1.0.1.  This was the first time the OpenStudio SketchUp Extension was submitted to the SketchUp extension warehouse.  The SketchUp team had a list of required changes (all good) that were required to accept the plug-in.  I made these changes then uploaded the modified rbz to the extension warehouse and the release page on GitHub.  We are working towards a 1.1.0 release that I will re-upload to the extension warehouse.  I will attempt to clean up the releases here to reflect this history better.

**Comment by macumber** [comment]
I cleaned up the release page and made a separate release for the SketchUp Extension warehouse v1.0.1 version.  Hopefully this process will go smoother starting in v1.1.0

**Comment by macumber** [comment]
I closed this issue but please re-open if there are further problems with the releases.

**Comment by camspiers** [comment]
Thanks!
