### ISSUE TITLE
OpenStudio plugin crashes Sketchup on Mac

### ISSUE THREAD

**Issue by anik120** [openstudiocoalition/openstudio-sketchup-plugin#67]
Hi guys, 

I installed Sketchup Studio 2019 and followed the installation steps [here](https://github.com/openstudiocoalition/openstudio-sketchup-plugin/releases/tag/v1.1.0) for installing the Openstudio plugin. However, when I click ok on the dialog box that appears for `Openstudio Root` that is automatically populated with `/Applications/OpenStudioApplication-1.1.0`, Sketchup crashes every single time, and the `BugsplatReporter` window shows up instead. 
<img width="1432" alt="Screen Shot 2020-11-15 at 7 02 05 PM" src="https://user-images.githubusercontent.com/3811058/99200838-ba964800-2775-11eb-9c66-7a43b6466142.png">

Here's how my Application folder looks like: 

```bash
$ ls /Applications/                            
Autodesk			Microsoft Excel.app		Microsoft Teams.app		OpenStudioApp			SketchUp 2019			Utilities
GarageBand.app			Microsoft OneNote.app		Microsoft Word.app		OpenStudioApplication-1.1.0	Skype.app			WhatsApp.app
Honey.app			Microsoft Outlook.app		Numbers.app			Pages.app			Slack.app			iMovie.app
Keynote.app			Microsoft PowerPoint.app	OneDrive.app			Safari.app			Spotify.app			zoom.us.app
```

How do I debug why I can't get the extension to load up? 

Additional information: 
OS: macOS Catalina 
Sketchup version: tried it with both 2019 and 2020 with the same result

**Comment by macumber** [comment]
Did you try entering the full path `/Applications/OpenStudioApplication-1.1.0`?

**Comment by anik120** [comment]
@macumber that is auto populated to `/Applications/OpenStudioApplication-1.1.0` you just can't see it in the screen shot coz the string is too long to fit in the text box.

**Comment by tacoktacok** [comment]
Hey, I'm having the exact same problem in OSX, have you found the solution yet?

**Comment by macumber** [comment]
I am seeing this on Mac now too.  It appears that no Ruby methods are being loaded out of openstudio_modeleditor.bundle.  This seems like it is new behavior, possibly a difference between the CI servers and my local build?

**Comment by macumber** [comment]
Unfortunately it looks like something broke with the plug-in when we updated from Qt 5.11 to 5.15.  I will look into this, in the meantime I suggest you link the plug-in to OpenStudioApplication 1.0.0.

**Comment by macumber** [comment]
Possibly related to https://bugs.launchpad.net/mixxx/+bug/1871238

**Comment by macumber** [comment]
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
  * frame #0: 0x00007fff2f4bacf8 CoreFoundation`CFBundleCopyBundleURL + 9
    frame #1: 0x0000000112c96930 QtCore`QLibraryInfo::location(QLibraryInfo::LibraryLocation) + 1328
    frame #2: 0x0000000112c96b8d QtCore`QLibraryInfo::location(QLibraryInfo::LibraryLocation) + 1933
    frame #3: 0x0000000112e7b7c4 QtCore`QCoreApplication::libraryPathsLocked() + 1524
    frame #4: 0x0000000112e778bb QtCore`QCoreApplication::libraryPaths() + 43
    frame #5: 0x0000000112e66424 QtCore`QFactoryLoader::update() + 36
    frame #6: 0x0000000112e67d10 QtCore`QFactoryLoader::QFactoryLoader(char const*, QString const&, Qt::CaseSensitivity) + 224
    frame #7: 0x0000000112619c3c QtGui`QGlobalStatic<QFactoryLoader, (anonymous namespace)::Q_QGS_loader::innerFunction(), (anonymous namespace)::Q_QGS_loader::guard>::operator()() + 172
    frame #8: 0x0000000112619ff1 QtGui`QPlatformIntegrationFactory::keys(QString const&) + 785
    frame #9: 0x0000000112626f5a QtGui`QGuiApplicationPrivate::createPlatformIntegration() + 1690
    frame #10: 0x00000001126284fb QtGui`QGuiApplicationPrivate::createEventDispatcher() + 27
    frame #11: 0x0000000112e774ef QtCore`QCoreApplicationPrivate::init() + 1599
    frame #12: 0x0000000112622c59 QtGui`QGuiApplicationPrivate::init() + 57
    frame #13: 0x0000000111fca0ca QtWidgets`QApplicationPrivate::init() + 26
    frame #14: 0x000000010d255de3 openstudio_modeleditor.bundle`openstudio::ApplicationSingleton::application(bool) + 5443
    frame #15: 0x000000010d222821 openstudio_modeleditor.bundle`_wrap_ApplicationSingleton_application(int, unsigned long*, unsigned long) + 625
    frame #16: 0x0000000100300b26 libruby.2.5.dylib`vm_call_cfunc [inlined] vm_call_cfunc_with_frame(ec=0x0000000100707408, reg_cfp=<unavailable>, ci=0x00000001006c2990) at vm_insnhelper.c:1918:11
    frame #17: 0x0000000100300a59 libruby.2.5.dylib`vm_call_cfunc(ec=0x0000000100707408, reg_cfp=<unavailable>, calling=<unavailable>, ci=0x00000001006c2990, cc=<unavailable>) at vm_insnhelper.c:1934
    frame #18: 0x00000001002e8e13 libruby.2.5.dylib`vm_exec_core(ec=<unavailable>, initial=<unavailable>) at insns.def:915:5
    frame #19: 0x00000001002fb218 libruby.2.5.dylib`vm_exec(ec=0x0000000100707408) at vm.c:1778:11
    frame #20: 0x000000010018e00f libruby.2.5.dylib`ruby_exec_internal(n=0x0000000101845358) at eval.c:247:2
    frame #21: 0x000000010018df08 libruby.2.5.dylib`ruby_run_node [inlined] ruby_exec_node(n=<unavailable>) at eval.c:311:12
    frame #22: 0x000000010018defa libruby.2.5.dylib`ruby_run_node(n=<unavailable>) at eval.c:303
    frame #23: 0x0000000100000f2f ruby`main(argc=<unavailable>, argv=<unavailable>) at main.c:42:9
    frame #24: 0x00007fff6963ccc9 libdyld.dylib`start + 1
    frame #25: 0x00007fff6963ccc9 libdyld.dylib`start + 1
(lldb) inspect

**Comment by macumber** [comment]
@anik120 @tacoktacok can you try installing https://github.com/openstudiocoalition/OpenStudioApplication/releases/download/v1.1.0/OpenStudioApplication-1.1.0+523d4118c0-Darwin.dmg and see if that fixes the issue?

**Comment by anik120** [comment]
@macumber it's working for me now! Thanks a lot for addressing it, I'm keeping this issue open because I'm guessing when your PR merges this issue will close along with it. 

Thanks again.

**Comment by macumber** [comment]
Awesome thanks! I'm going to tag a new release with this fix.  This was a nasty bug due to upgrading our version of Qt, thanks for reporting it!

**Comment by DavidGoldwasser** [comment]
Mac SketchUp 2020 worked for me as well with this OS App dmg

**Comment by Anna-Cn** [comment]
Hi @anik120, could you please explain to me how did you solve the problem? Thanks.

**Comment by sashganguly** [comment]
> @anik120 @tacoktacok can you try installing https://github.com/openstudiocoalition/OpenStudioApplication/releases/download/v1.1.0/OpenStudioApplication-1.1.0+523d4118c0-Darwin.dmg and see if that fixes the issue?

Hi, I had the exact same issue for Sketchup 2019 and 2020 (tried both). And then followed this thread and could not access the link for the dmg you mentioned. Page not found

**Comment by macumber** [comment]
I think we re-released that as v1.1.1-alpha1, can you try downloading from the following links:

https://github.com/openstudiocoalition/OpenStudioApplication/releases/tag/v1.1.1-alpha1
https://github.com/openstudiocoalition/OpenStudioApplication/releases/download/v1.1.1-alpha1/OpenStudioApplication-1.1.0+bbbd1d3e07-Darwin.dmg

**Comment by macumber** [comment]
I've retagged this release as v1.1.1 so it doesn't get lost again

https://github.com/openstudiocoalition/OpenStudioApplication/releases/tag/v1.1.1

**Comment by sashganguly** [comment]
Thanks @macumber for this. I have been in hospital since the last few weeks so couldn't manage to try it. Should finally get to check it out next week and will let you know how it went. Much appreciate your prompt fix!

**Comment by dmacusb2** [comment]
I’m glad you are doing better!

**Comment by macumber** [comment]
I’m glad you are feeling better!
