### ISSUE TITLE
OpenStudio SketchUp Plug-in doesn't work in SketchUp 2021

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/openstudio-sketchup-plugin#68]
OpenStudio Application v1.1.0 is based on OpenStudio 3.1.0 which is built using Ruby 2.5.5.  SketchUp 2021 upgraded to Ruby 2.7.1 which is incompatible with Ruby 2.5.5.  There is an [enhancement request](https://github.com/NREL/OpenStudio/issues/4134) to upgrade OpenStudio's Ruby version to 2.7.1 for a future release.

**Comment by macumber** [comment]
Fixed in OS App v1.2.0-RC1

**Comment by BsanmarE** [comment]
Where can I download the best suitable openstudio version for SU2021?

Any link available.

Thank you

**Comment by macumber** [comment]
See the [SketchUp Plug-in Version Compatibility Matrix](https://github.com/openstudiocoalition/openstudio-sketchup-plugin/wiki/OpenStudio-SketchUp-Plug-in-Wiki#openstudio-sketchup-plug-in-version-compatibility-matrix)

OpenStudio Application releases are available at https://github.com/openstudiocoalition/OpenStudioApplication/releases
