### ISSUE TITLE
OpenStudio plugin crashes Sketchup on Mac

### ISSUE THREAD

**Issue by Anna-Cn** [openstudiocoalition/openstudio-sketchup-plugin#69]
Hi guys,

I installed Sketchup Studio 2020 and followed the installation steps for installing the Openstudio plugin. However, when I click ok on the dialog box that appears for Openstudio Root that is automatically populated with /Applications/OpenStudioApplication-1.1.0, Sketchup crashes every single time, and the BugsplatReporter window shows up instead.

I saw that someone solved this problem using this link https://github.com/openstudiocoalition/OpenStudioApplication/releases/download/v1.1.0/OpenStudioApplication-1.1.0+523d4118c0-Darwin.dmg 

 but now this link reminds to a page that does not exist.

Does anyone have another link that may work?

Many thanks.

**Comment by macumber** [comment]
Hi @Anna-Cn can you try downloading from this link:

https://github.com/openstudiocoalition/OpenStudioApplication/releases/tag/v1.1.1-alpha2

**Comment by Anna-Cn** [comment]
Hi Dan,

thank you so much for your reply.

It worked.

Best regards,
Anna

**Comment by 4sidmodi** [comment]
Hey, i have same problem in mac but when i installed v1.1.1 and then try to do openstudio plugin path that automatically pop up. But then after message comes up that "New-plugin version detected, resetting preferences and when i hit ok then sketchup suddenly freeze. 
![WhatsApp Image 2021-09-09 at 11 53 11 PM](https://user-images.githubusercontent.com/90442241/132812770-4c2ab47e-40d9-4e1a-a5d4-81f855494011.jpeg)

**Comment by macumber** [comment]
@4sidmodi can you try the new version 1.2.1?
