### ISSUE TITLE
Enhancement: Intersect and Surface Matching

### ISSUE THREAD

**Issue by Ski90Moo** [openstudiocoalition/openstudio-sketchup-plugin#75]
The intersect and surface matching seems to work way better when you do it space-by-space instead of trying to do the whole model at the same time.  I am wondering if it is possible to write a user script that does this function for the whole model, but it only executes intersect and match one space at a time?

**Comment by macumber** [comment]
That is what the `IntersectSpaceGeometry` script does:

https://github.com/openstudiocoalition/openstudio-sketchup-plugin/blob/develop/plugin/openstudio/user_scripts/Alter%20or%20Add%20Model%20Elements/Intersect_Space_Geometry.rb#L75

**Comment by macumber** [comment]
You could try sorting the spaces to intersect in a better order since the intersection results are dependent on the order they happen, we did that here to some extent:

https://github.com/NREL/OpenStudio/blob/develop/src/model/Space.cpp#L3289
https://github.com/NREL/OpenStudio/blob/develop/src/model/Space.cpp#L2223

**Comment by Ski90Moo** [comment]
Ok; for some reason the script seems to always freeze when surface matching the entire model, or if there are a very large number of spaces.  There always seems to be errors associated with matching some surfaces.  It seems if there are too many errors, then SketchUp just freezes. I am wondering if there is a way for the script to detect an error and stop running before it tries to surface match additional spaces?

**Comment by macumber** [comment]
It probably could, the problem is identifying the situation that indicates an error has (or better is likely to) occur
