### ISSUE TITLE
OpenStudio Inspector does not support Imported Space Loads

### ISSUE THREAD

**Issue by eomere** [openstudiocoalition/openstudio-sketchup-plugin#8]
The OpenStudio Inspector does not support Space Loads. Hence, a User cannot access imported Space Loads (**Extensions/OpenStudio/Import/Import Space Loads**). The issue is present within both the Mac and Windows versions of the Plugin.

Will this feature be removed from menu options, or will the OpenStudio Inspector be updated to support Space Loads?

**Comment by jmarrec** [comment]
I thought originally you meant when importing from IDF, the loads (equipment, people, etc) isn't viewable (but it is in the OS Application), but I later realized you meant this:

![image](https://user-images.githubusercontent.com/5479063/77421882-e91d7800-6dcc-11ea-9e57-242a850c6a7e.png)

So I thought this was a valid point: Constructions can be assigned to ConstructionSets and surfaces, Schedules can be set on the Default:ScheduleSet, but loads no.

After digging, this is actually just very badly named, and what it does is import **Space Types** from a custom OSM file.

**Comment by eomere** [comment]
Good catch
