### ISSUE TITLE
OpenStudio-Sketchup-Plugin door couldn't be recognized when creating a new space

### ISSUE THREAD

**Issue by Cyy-fresh1994** [openstudiocoalition/openstudio-sketchup-plugin#82]
Hi, when I tried to build the building geometry by using the OpenStudio-Sketchup-Plugin, I met with some problems.

I installed the Sketchup 2021, OpenStudio application 1.2.0, and OpenStudio-Sketchup-Plugin 1.2.0. After I create a new space by using the plugin, I draw a window on the wall, the window could be recognized, but when I was trying to draw a door, the door was still recognized as a window, not a door. 

Did something changed with the new version, or is it some errors?

**Comment by macumber** [comment]
This does seem to be a new issue.  We will try to fix this in the next release.  In the meantime you can use the Inspector to change the SubSurface Type from FixedWindow to Door

**Comment by macumber** [comment]
Seems to be caused by https://github.com/NREL/OpenStudio/commit/0c61eb912447f2db5dfb10da4e88025fab74d76a#diff-22d1a408ca40f2b5bec82da19360b7e1e78288afa590a832837dfc6f6cd2d8d4
