### ISSUE TITLE
Surface searching doesn't work in openstudio-sketchup-plugin

### ISSUE THREAD

**Issue by Cyy-fresh1994** [openstudiocoalition/openstudio-sketchup-plugin#83]
Hi I am having another issue while using openstudio-sketchup-plugin 1.2.0

When I tried to do surface search, the interface comes as follows:
![image](https://user-images.githubusercontent.com/66685387/122110411-7ee75d80-cdec-11eb-9937-6518024d11bf.png)

I couldn't find any surface in the model. Why did this happen?

**Comment by macumber** [comment]
I think the only issue here is that you need to choose the object class (OS:Surface, OS:SubSurface, etc) before the other fields become active.  You just need to resize the window or scroll up to set the object class.
