### ISSUE TITLE
SketchUp issues when selecting thermal zone

### ISSUE THREAD

**Issue by Ski90Moo** [openstudiocoalition/openstudio-sketchup-plugin#87]
When render by thermal zone is selected, it will not show the thermal zone in the inspector tool.  If I select other thermal zones, it continues to cause issues and eventually crashes.
![2021-07-15 (1)_LI](https://user-images.githubusercontent.com/69771412/125884263-7866d1d8-3507-4cfd-b377-244d2f6539b8.jpg)
![2021-07-15 (2)](https://user-images.githubusercontent.com/69771412/125884299-12bd6152-a984-4aca-ad0f-a26398c185aa.png)
![2021-07-15 (4)](https://user-images.githubusercontent.com/69771412/125884333-52c982ad-5e94-41f5-910d-1b86760c1541.png)

From the Ruby console:
ERROR:
RuntimeError
bad allocation
BACKTRACE:
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/DialogManager.rb:321:in `setIddObjectType'
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/DialogManager.rb:321:in `selection_changed'
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/interfaces/MaterialsInterface.rb:371:in `rendering_mode='
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/MenuManager.rb:508:in `block (2 levels) in create_commands'
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/PluginManager.rb:260:in `block in process_events'
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/PluginManager.rb:253:in `each'
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/PluginManager.rb:253:in `process_events'
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/PluginManager.rb:312:in `block in start_event_processing'
Error: #<RuntimeError: bad allocation>
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/DialogManager.rb:321:in `setIddObjectType'
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/DialogManager.rb:321:in `selection_changed'
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/observers/SelectionObserver.rb:84:in `onSelectionBulkChange'
Error: #<RuntimeError: bad allocation>
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/DialogManager.rb:321:in `setIddObjectType'
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/DialogManager.rb:321:in `selection_changed'
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/observers/SelectionObserver.rb:84:in `onSelectionBulkChange'
Error: #<RuntimeError: bad allocation>
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/DialogManager.rb:321:in `setIddObjectType'
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/DialogManager.rb:321:in `selection_changed'
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/observers/SelectionObserver.rb:84:in `onSelectionBulkChange'
Error: #<RuntimeError: bad allocation>
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/DialogManager.rb:321:in `setIddObjectType'
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/DialogManager.rb:321:in `selection_changed'
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/observers/SelectionObserver.rb:84:in `onSelectionBulkChange'
Error: #<RuntimeError: bad allocation>
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/DialogManager.rb:321:in `setIddObjectType'
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/DialogManager.rb:321:in `selection_changed'
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/observers/SelectionObserver.rb:84:in `onSelectionBulkChange'
Error: #<RuntimeError: bad allocation>
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/DialogManager.rb:321:in `setIddObjectType'
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/DialogManager.rb:321:in `selection_changed'
C:/Users/owner/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/observers/SelectionObserver.rb:84:in `onSelectionBulkChange'

**Comment by macumber** [comment]
Thanks for another great report @Ski90Moo, this is actually caused by an issue in the app repo: https://github.com/openstudiocoalition/OpenStudioApplication/issues/401
